// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               v6.33.0
// source: chat/v1/message.proto

/* eslint-disable */
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "chat.v1";

export enum ChunkType {
  CHUNK_TYPE_UNSPECIFIED = 0,
  TYPE_TOKEN = 1,
  TYPE_NODE_COMPLETE = 2,
  UNRECOGNIZED = -1,
}

export interface ChatMessageRequest {
  userId: string;
  message: string;
  agent: string;
  timestamp: number;
}

export interface ErrorInfo {
  code: string;
  message: string;
}

export interface ChatChunkResponse {
  token: string;
  type: ChunkType;
  node: string;
  error?: ErrorInfo | undefined;
  isFinal: boolean;
  timestamp: Timestamp | undefined;
}

export const CHAT_V1_PACKAGE_NAME = "chat.v1";
