// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               v6.33.0
// source: chat/v1/service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { ChatChunkResponse, ChatMessageRequest } from "./message";

export const protobufPackage = "chat.v1";

export const CHAT_V1_PACKAGE_NAME = "chat.v1";

export interface ChatServiceClient {
  chatStream(request: Observable<ChatMessageRequest>): Observable<ChatChunkResponse>;
}

export interface ChatServiceController {
  chatStream(request: Observable<ChatMessageRequest>): Observable<ChatChunkResponse>;
}

export function ChatServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ChatService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = ["chatStream"];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ChatService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CHAT_SERVICE_NAME = "ChatService";
